name: Docker Cancer Trainer (scoped)

on:
  push:
    branches: [ "main" ]
    paths:
      - 'Labs/Docker_Cancer_Trainer/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'Labs/Docker_Cancer_Trainer/**'
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "✅ Lab workflow runs and passes"
