name: Testing with Pytest
on: { push: { branches: ["main"] }, pull_request: { branches: ["main"] } }
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: python -m pip install --upgrade pip
      - run: pip install -r requirements.txt
      - run: pytest -q --junitxml=pytest-report.xml
      - uses: actions/upload-artifact@v4
        with: { name: test-results, path: pytest-report.xml }
