name: Python Unittests

on:
  push:
    branches: ["main"]
    paths-ignore:
      - 'Labs/Docker_Cancer_Trainer/**'
      - '.github/**'
  pull_request:
    branches: ["main"]
    paths-ignore:
      - 'Labs/Docker_Cancer_Trainer/**'
      - '.github/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Run unittest (skip if none)
        shell: bash
        run: |
          if ls test/test_unittest.py >/dev/null 2>&1 || ls test/*.py >/dev/null 2>&1; then
            python -m unittest discover -s test -p "test_unittest.py" -v
          else
            echo "No unittest files found, skipping."
          fi
